apiVersion: v1
kind: Service
metadata:
  name: {{ include "gha-exporter.fullname" . }}
  labels:
    {{- include "gha-exporter.labels" . | nindent 4 }}
    jobLabel: node-exporter
    app.kubernetes.io/component: metrics
    release: gha-exporter
  annotations:
     prometheus.io/scrape: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gha-exporter.selectorLabels" . | nindent 4 }}
